### ISSUE TITLE
你好，请问可以在API服务上加一个非流式结果吗？

### ISSUE THREAD

**Issue by luosaidage** [yuri2peter/my-chatglm2#2]
如题。
目前的好像只有流式回答。

**Comment by yuri2peter** [comment]
的确。我抽空加一下

**Comment by yuri2peter** [comment]
V1.1已完成该需求：https://github.com/yuri2peter/my-chatglm2/commit/d472fa7efb648a838c61ed9c3163bb3897fac107
注意客户端也要升级到V1.1
